### ISSUE TITLE
Remove the multiple checks wether showing Urban Dictionary is ok

### ISSUE THREAD

**Issue by llrs** [r-lib/available#49]
get_urban_data checks with the user if they want to include Urban dictionary as a source. Because:

> Urban Dictionary can contain potentially offensive results,
  should they be included? [Y]es / [N]o:

However I got asked 5 times! (Which I think it is too much..) Could that check be done before the `lappy` call and just once? 

I could submit a PR to change this: 
https://github.com/ropenscilabs/available/blob/57c04c32f14ade8eb72b568a434dbbe36c3c9365/R/available.R#L36-L46

**Comment by jimhester** [comment]
Sure, a PR would be great!

**Comment by mjsteinbaugh** [comment]
I'm interested in fixing this too -- I'll see if I can make a PR when I have some free time.

**Comment by llrs** [comment]
@mjsteinbaugh see the PR #50, it missed the release so you'll need to install the latest from github or wait for the next CRAN release. I think it was already solved but if you think that stills needs some tweaks go ahead
