### ISSUE TITLE
ropenscilabs or ropensci?

### ISSUE THREAD

**Issue by jennybc** [r-lib/available#57]
Now that available is on CRAN, should it be moved to ropensci?

Context: I plan to mention available in the 2nd edition of R Packages, hence my interest in the signals around its level of maturity and support.

**Comment by jimhester** [comment]
@maelle, what would be the process for getting this moved? Would available need to go through the full rOpenSci package review process?

**Comment by noamross** [comment]
@maelle is still leave so I'll chime in 🙂.  I suggest moving `available` to your personal account or perhaps the r-lib organization.  Repos under ropensci are either staff-maintained or peer-reviewed, and I don't believe this is in-scope for peer review.

**Comment by jimhester** [comment]
Ok I moved it to r-lib.

**Comment by noamross** [comment]
👍 May it have a long and happy life in its new home!
