### ISSUE TITLE
Says available when it is not available in GitHub

### ISSUE THREAD

**Issue by sevvandi** [r-lib/available#65]
Hi,

My R package lookout is public and is at https://github.com/sevvandi/lookout.  When I check if the name is available, it says it is. Why is that?  Can it be fixed?

Thanks,
Sevvandi

**Comment by jimhester** [comment]
available uses the API at http://rpkg.gepuro.net/ to check if an R package is on GitHub. That service in turn relies on GitHub's code classification of a repository, and your repository does not have enough R code for GitHub to classify it as R.

**Comment by dfalster** [comment]
I have this issue too, shows as available on GitHub when it's not: https://github.com/traitecoevo/plant. 

It's an R package has lots of C++, so perhaps get's classified primarily as C++? 

`available` is a great package, helping to enhance compatibility across CRAN, GitHub etc. But I'm now worried `available` will give people false confidence of using a taken name. If I understand your response above @jimhester - really needs to be fixed upstream in API for http://rpkg.gepuro.net/?

I've started by contacting the dev there, see https://twitter.com/adaptive_plant/status/1366861287452418048

**Comment by jimhester** [comment]
GitHub uses https://github.com/github/linguist to classify repos. It is possible to use a `.gitattributes` file to explicitly set the classification for files in your repository if they are being misclassified, but if the files are correctly classified and you just have more C++ code than R code there is not much that can be done.

False positives for GitHub repositories are just going to happen, the only sure way you can 'claim' a name is by submitting the package to CRAN or Bioconductor.

**Comment by dfalster** [comment]
Thanks @jimhester.

Thanks to helpful changes implemented by [@gepuro](https://twitter.com/gepuro) in http://rpkg-api.gepuro.net today, this is now solved for my package. Here it is working from my repo, `traitecoevo/plant`:
![image](https://user-images.githubusercontent.com/3589590/110296952-0a5f8e80-8047-11eb-9a33-29c9401ab657.jpeg)

[@gepuro](https://twitter.com/gepuro) reported making  two changes in rpkg-api.gepuro.net that got things working for me:
1) Changed crawling logic to include Rcpp projects
2) Removed a limit on number of results returned when querying the API, which was previously only returning the first 100 results (searching on "plant" returns quite a list fo packages). 

These issues presumably excluded a bunch of packages (not just mine).
