### ISSUE TITLE
Add fastmap and cachem to imports

### ISSUE THREAD

**Issue by ebenp** [r-lib/available#70]
Hi,

I needed to install fastmap and cachem before available would run. I suggest you add them as imports.

> library(available)
Warning message:
package ‘available’ was built under R version 4.0.4 
Warning: namespace ‘fastmap’ is not available and has been replaced
by .GlobalEnv when processing object ‘<unknown>’
Warning: namespace ‘cachem’ is not available and has been replaced
by .GlobalEnv when processing object ‘<unknown>’
Warning: namespace ‘fastmap’ is not available and has been replaced
by .GlobalEnv when processing object ‘<unknown>’
Warning: namespace ‘cachem’ is not available and has been replaced
by .GlobalEnv when processing object ‘<unknown>’
Warning: namespace ‘fastmap’ is not available and has been replaced
by .GlobalEnv when processing object ‘<unknown>’
Warning: namespace ‘cachem’ is not available and has been replaced
by .GlobalEnv when processing object ‘<unknown>’
Warning: namespace ‘fastmap’ is not available and has been replaced
by .GlobalEnv when processing object ‘<unknown>’
Warning: namespace ‘cachem’ is not available and has been replaced
by .GlobalEnv when processing object ‘<unknown>’

When running available("packagename") I got
Error in validate_key(key) : could not find function "validate_key"

**Comment by jimhester** [comment]
These are transitive dependencies of memoise, they would have been automatically installed when installing the current version of memoise, so I don't think there is anything we would need to do here.
