### ISSUE TITLE
GitHub availability is incorrect - oddnet R package

### ISSUE THREAD

**Issue by sevvandi** [r-lib/available#79]
Hi, 

I have an R package on GitHub oddnet https://github.com/sevvandi/oddnet. But package available says the name oddnet is available on Github.  How can this be fixed?

Thanks,
Sevvandi

**Comment by gaborcsardi** [comment]
Available queries http://rpkg-api.gepuro.net/rpkg?q=oddnet and that service might be out of date, or just not updated frequently. 

Availability on GitHub is a weird thing, anyway. Nobody stops you from creating a package with the same name.
