### ISSUE TITLE
function available don't work

### ISSUE THREAD

**Issue by GuilhermeFCO** [r-lib/available#81]
Function available and available_on_cran don't work, but available_on_github and available_on_bioc work.

Error message:
Error in readRDS(con) : error reading from connection

**Comment by gaborcsardi** [comment]
Seems to work here:
```
❯ available::available_on_cran("foo")
Available on CRAN: ✔
```

If it does not work for you, maybe the mirror you are using is down.

Btw. the `pak::pkg_name_check()` function does a much better job than available, so it is probably better to switch to that:

<img width="1002" alt="Screen Shot 2022-10-19 at 11 56 13 PM" src="https://user-images.githubusercontent.com/660288/196812363-f2c0e854-dca7-4200-b8fe-57bed8731beb.png">
